In [114]:
# Cargamos Pandas para abir el archivo CSV y ponemos la primera columna como indice ya que es una serie de tiempo
import pandas as pd
df = pd.read_csv("25001edit.csv", index_col=0)
# Mostramos los primeros 5 registros
df.head(5)

           PRECIP  EVAP  TMAX TMIN
FECHA
01/01/1961      0  Nulo    25   13
02/01/1961      0  Nulo  27.5   14
03/01/1961      0  Nulo    31   11
04/01/1961      0  Nulo    32   13
05/01/1961      0  Nulo    29   14

In [115]:
# Mostramos los ultimos 5 registros
df.tail(5)

           PRECIP EVAP TMAX  TMIN
FECHA
27/07/2018    2.3  0.6   37    19
28/07/2018    9.8  3.7   37  23.5
29/07/2018      6  3.3   35    20
30/07/2018     48    6   36    22
31/07/2018      2  3.7   34    22

In [116]:
# Mostramos el numero de filas y columnas
print(df.shape)

(19574, 4)

In [117]:
# Mostramos informacion general como el tipo de datos, valores nulos, etc
df.info()

# Podemos apreciar que no hay valores nulos, esto es debido a que los "nulo" del archivo
# se consideran datos tipo String, mas adelante cambiaremos eso

<class 'pandas.DataFrame'>
Index: 19574 entries, 01/01/1961 to 31/07/2018
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PRECIP  19574 non-null  str
 1   EVAP    19574 non-null  str
 2   TMAX    19574 non-null  str
 3   TMIN    19574 non-null  str
dtypes: str(4)
memory usage: 764.6+ KB

In [118]:
# Aqui apreciamos como todas las columnas son tipo String a causa de los "Nulo"
df.dtypes

PRECIP    str
EVAP      str
TMAX      str
TMIN      str
dtype: object

In [119]:
# Mostramos el numero de nulos 
df.isnull().sum()
# Aqui sucede lo mismo ya comentado, de momento no hay nulos

PRECIP    0
EVAP      0
TMAX      0
TMIN      0
dtype: int64

In [120]:
# Investigando con ayuda de la IA encontramos la funcion describe() la cual nos da un resumen estadistico
# descriptivo del dataframe, decidimos utilizarlo ya que nos servira para poder notar la diferencia
# entre un dataframe con objetos tipo String (el de este momento) y uno de tipo Numerico (mas adelante)

# Mostramos las descripciones estadisticas de las columnas numericas
df.describe()

       PRECIP   EVAP   TMAX   TMIN
count   19574  19574  19574  19574
unique    493    135     60     63
top         0      3     35     23
freq    16087    401   1980   1225

In [121]:
# Cargamos Numpy ya que cuenta con funciones que nos va a servir para nuestro preprocesamiento de datos
import numpy as np
# Reemplazamos los valores "Nulo" por NaN para que Pandas los reconozca como valores faltantes
df.replace("Nulo", np.nan, inplace=True)

           PRECIP EVAP  TMAX  TMIN
FECHA
01/01/1961      0  NaN    25    13
02/01/1961      0  NaN  27.5    14
03/01/1961      0  NaN    31    11
04/01/1961      0  NaN    32    13
05/01/1961      0  NaN    29    14
...           ...  ...   ...   ...
27/07/2018    2.3  0.6    37    19
28/07/2018    9.8  3.7    37  23.5
29/07/2018      6  3.3    35    20
30/07/2018     48    6    36    22
31/07/2018      2  3.7    34    22

[19574 rows x 4 columns]

In [122]:
# Mostramos el numero de nulos (ahora ya existen)
df.isnull().sum()

PRECIP     40
EVAP      272
TMAX        5
TMIN        6
dtype: int64

In [123]:
# Convertimos las columnas a tipo numerico para poder trabajar con ellas
# el metodo to_numeric no fue visto en clase pero es necesario para poder trabajar con los datos
df["PRECIP"] = pd.to_numeric(df["PRECIP"])
df["EVAP"] = pd.to_numeric(df["EVAP"])
df["TMIN"] = pd.to_numeric(df["TMIN"])
df["TMAX"] = pd.to_numeric(df["TMAX"])

In [124]:
# En este punto los datos ya estan listos para trabajar en ellos,
# Son tipo numericos y contiene nulos reales
df.dtypes

PRECIP    float64
EVAP      float64
TMAX      float64
TMIN      float64
dtype: object

In [125]:
# Mostramos los primeros 5 registros una vez procesados los datos
df.head(5)

            PRECIP  EVAP  TMAX  TMIN
FECHA
01/01/1961     0.0   NaN  25.0  13.0
02/01/1961     0.0   NaN  27.5  14.0
03/01/1961     0.0   NaN  31.0  11.0
04/01/1961     0.0   NaN  32.0  13.0
05/01/1961     0.0   NaN  29.0  14.0

In [126]:
# Mostramos las ultimas 5 registros una vez procesados los datos
df.tail(5)

            PRECIP  EVAP  TMAX  TMIN
FECHA
27/07/2018     2.3   0.6  37.0  19.0
28/07/2018     9.8   3.7  37.0  23.5
29/07/2018     6.0   3.3  35.0  20.0
30/07/2018    48.0   6.0  36.0  22.0
31/07/2018     2.0   3.7  34.0  22.0

In [127]:
# Mostramos un resumen de los datos una vez procesados los datos
# En este punto ya considera que algunos son nulos y no los suma
df.info()

<class 'pandas.DataFrame'>
Index: 19574 entries, 01/01/1961 to 31/07/2018
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   PRECIP  19534 non-null  float64
 1   EVAP    19302 non-null  float64
 2   TMAX    19569 non-null  float64
 3   TMIN    19568 non-null  float64
dtypes: float64(4)
memory usage: 764.6+ KB

In [128]:
# Mostramos el numero de filas y columnas (no ha cambiado)
df.shape

(19574, 4)

In [129]:
# Mostramos las descripciones estadisticas una vez procesados los datos
# Como ya estan seteados los datos a tipo numerico con nulos, ahora si nos aparece la informacion completa
# del metodo describe()
df.describe()

             PRECIP          EVAP          TMAX          TMIN
count  19534.000000  19302.000000  19569.000000  19568.000000
mean       2.217452      4.882157     34.468808     16.657420
std        9.015782      2.279340      3.430054      6.248605
min        0.000000      0.000000     18.000000     -2.500000
25%        0.000000      3.200000     32.500000     11.000000
50%        0.000000      4.500000     35.000000     16.500000
75%        0.000000      6.500000     37.000000     23.000000
max      217.400000     15.600000     45.500000     29.000000

In [130]:
# "2.- Contar total de registros faltantes por fecha"

# Obtenemos todas las filas que vamos a trabajar
total_filas = df.shape[0]

# Por medio de un for interamos sobre cada fila para contar el numero de nulos que tienen por fila
for i in range(total_filas):
    fila = df.iloc[i]
    
    total_columnas = fila.shape[0]                      # Ya sabemos que es 4 pero lo correcto es calcularlo
    elementos_validos = fila.dropna().shape[0]          # Contamos solo los elementos no nulos
    faltantes = total_columnas - elementos_validos      # Calculamos el numero de nulos
    
    # Mostramos solo si hay nulos para no saturar la pantalla
    if faltantes > 0:
        print(f"{df.index[i]} | Registros faltantes: {faltantes}")

01/01/1961 | Registros faltantes: 1
02/01/1961 | Registros faltantes: 1
03/01/1961 | Registros faltantes: 1
04/01/1961 | Registros faltantes: 1
05/01/1961 | Registros faltantes: 1
06/01/1961 | Registros faltantes: 1
07/01/1961 | Registros faltantes: 1
08/01/1961 | Registros faltantes: 1
09/01/1961 | Registros faltantes: 1
10/01/1961 | Registros faltantes: 1
11/01/1961 | Registros faltantes: 1
12/01/1961 | Registros faltantes: 1
13/01/1961 | Registros faltantes: 1
14/01/1961 | Registros faltantes: 1
15/01/1961 | Registros faltantes: 1
16/01/1961 | Registros faltantes: 1
17/01/1961 | Registros faltantes: 1
18/01/1961 | Registros faltantes: 1
19/01/1961 | Registros faltantes: 1
20/01/1961 | Registros faltantes: 1
21/01/1961 | Registros faltantes: 1
22/01/1961 | Registros faltantes: 1
23/01/1961 | Registros faltantes: 1
24/01/1961 | Registros faltantes: 1
25/01/1961 | Registros faltantes: 1
26/01/1961 | Registros faltantes: 1
27/01/1961 | Registros faltantes: 1
28/01/1961 | Registros faltantes: 1
29/01/1961 | Registros faltantes: 1
30/01/1961 | Registros faltantes: 1
31/01/1961 | Registros faltantes: 1
01/02/1961 | Registros faltantes: 1
02/02/1961 | Registros faltantes: 1
03/02/1961 | Registros faltantes: 1
04/02/1961 | Registros faltantes: 1
05/02/1961 | Registros faltantes: 1
06/02/1961 | Registros faltantes: 1
07/02/1961 | Registros faltantes: 1
08/02/1961 | Registros faltantes: 1
09/02/1961 | Registros faltantes: 1
10/02/1961 | Registros faltantes: 1
11/02/1961 | Registros faltantes: 1
12/02/1961 | Registros faltantes: 1
13/02/1961 | Registros faltantes: 1
14/02/1961 | Registros faltantes: 1
15/02/1961 | Registros faltantes: 1
16/02/1961 | Registros faltantes: 1
17/02/1961 | Registros faltantes: 1
18/02/1961 | Registros faltantes: 1
19/02/1961 | Registros faltantes: 1
20/02/1961 | Registros faltantes: 1
21/02/1961 | Registros faltantes: 1
22/02/1961 | Registros faltantes: 1
23/02/1961 | Registros faltantes: 1
24/02/1961 | Registros faltantes: 1
25/02/1961 | Registros faltantes: 1
26/02/1961 | Registros faltantes: 1
27/02/1961 | Registros faltantes: 1
28/02/1961 | Registros faltantes: 1
01/03/1961 | Registros faltantes: 1
22/04/1961 | Registros faltantes: 1
17/10/1962 | Registros faltantes: 1
13/12/1962 | Registros faltantes: 1
27/01/1963 | Registros faltantes: 1
06/03/1963 | Registros faltantes: 1
21/04/1963 | Registros faltantes: 1
29/05/1963 | Registros faltantes: 1
30/11/1964 | Registros faltantes: 1
01/03/1965 | Registros faltantes: 1
20/08/1965 | Registros faltantes: 1
30/11/1965 | Registros faltantes: 1
23/12/1965 | Registros faltantes: 1
31/01/1966 | Registros faltantes: 1
08/06/1966 | Registros faltantes: 1
25/06/1966 | Registros faltantes: 1
30/06/1966 | Registros faltantes: 1
14/12/1967 | Registros faltantes: 1
16/12/1967 | Registros faltantes: 1
14/11/1968 | Registros faltantes: 1
01/01/1969 | Registros faltantes: 1
06/02/1969 | Registros faltantes: 1
01/06/1969 | Registros faltantes: 1
02/06/1969 | Registros faltantes: 1
03/06/1969 | Registros faltantes: 1
04/06/1969 | Registros faltantes: 1
05/06/1969 | Registros faltantes: 1
06/06/1969 | Registros faltantes: 1
07/06/1969 | Registros faltantes: 1
08/06/1969 | Registros faltantes: 1
09/06/1969 | Registros faltantes: 1
10/06/1969 | Registros faltantes: 1
11/06/1969 | Registros faltantes: 1
12/06/1969 | Registros faltantes: 1
13/06/1969 | Registros faltantes: 1
14/06/1969 | Registros faltantes: 1
15/06/1969 | Registros faltantes: 1
16/06/1969 | Registros faltantes: 1
17/06/1969 | Registros faltantes: 1
18/06/1969 | Registros faltantes: 1
19/06/1969 | Registros faltantes: 1
20/06/1969 | Registros faltantes: 1
21/06/1969 | Registros faltantes: 1
22/06/1969 | Registros faltantes: 1
23/06/1969 | Registros faltantes: 1
24/06/1969 | Registros faltantes: 1
25/06/1969 | Registros faltantes: 1
26/06/1969 | Registros faltantes: 1
27/06/1969 | Registros faltantes: 1
28/06/1969 | Registros faltantes: 1
29/06/1969 | Registros faltantes: 1
30/06/1969 | Registros faltantes: 1
28/08/1969 | Registros faltantes: 1
28/02/1970 | Registros faltantes: 2
07/11/1974 | Registros faltantes: 1
08/11/1974 | Registros faltantes: 1
03/02/1975 | Registros faltantes: 1
30/04/1977 | Registros faltantes: 1
10/12/1982 | Registros faltantes: 1
26/12/1982 | Registros faltantes: 1
15/08/1991 | Registros faltantes: 1
26/05/1992 | Registros faltantes: 2
31/05/1992 | Registros faltantes: 1
17/06/1992 | Registros faltantes: 3
17/04/1999 | Registros faltantes: 3
24/04/1999 | Registros faltantes: 3
03/09/1999 | Registros faltantes: 1
19/10/2000 | Registros faltantes: 1
20/10/2000 | Registros faltantes: 1
21/10/2000 | Registros faltantes: 1
22/10/2000 | Registros faltantes: 1
23/10/2000 | Registros faltantes: 1
24/10/2000 | Registros faltantes: 1
25/10/2000 | Registros faltantes: 1
26/10/2000 | Registros faltantes: 1
27/10/2000 | Registros faltantes: 1
28/10/2000 | Registros faltantes: 1
29/10/2000 | Registros faltantes: 1
30/10/2000 | Registros faltantes: 1
31/10/2000 | Registros faltantes: 1
01/11/2000 | Registros faltantes: 1
02/11/2000 | Registros faltantes: 1
03/11/2000 | Registros faltantes: 1
04/11/2000 | Registros faltantes: 1
05/11/2000 | Registros faltantes: 1
06/11/2000 | Registros faltantes: 1
07/11/2000 | Registros faltantes: 1
08/11/2000 | Registros faltantes: 1
09/11/2000 | Registros faltantes: 1
10/11/2000 | Registros faltantes: 1
11/11/2000 | Registros faltantes: 1
12/11/2000 | Registros faltantes: 1
13/11/2000 | Registros faltantes: 1
14/11/2000 | Registros faltantes: 1
15/11/2000 | Registros faltantes: 1
16/11/2000 | Registros faltantes: 1
17/11/2000 | Registros faltantes: 1
31/07/2001 | Registros faltantes: 1
31/10/2001 | Registros faltantes: 1
31/01/2003 | Registros faltantes: 2
31/05/2003 | Registros faltantes: 1
31/07/2003 | Registros faltantes: 1
20/04/2005 | Registros faltantes: 1
31/08/2006 | Registros faltantes: 1
30/11/2007 | Registros faltantes: 1
26/06/2009 | Registros faltantes: 1
27/06/2009 | Registros faltantes: 1
28/06/2009 | Registros faltantes: 1
29/06/2009 | Registros faltantes: 1
30/06/2009 | Registros faltantes: 1
01/07/2009 | Registros faltantes: 1
02/07/2009 | Registros faltantes: 1
03/07/2009 | Registros faltantes: 1
04/07/2009 | Registros faltantes: 1
05/07/2009 | Registros faltantes: 1
06/07/2009 | Registros faltantes: 1
07/07/2009 | Registros faltantes: 1
08/07/2009 | Registros faltantes: 1
09/07/2009 | Registros faltantes: 1
10/07/2009 | Registros faltantes: 1
11/07/2009 | Registros faltantes: 1
12/07/2009 | Registros faltantes: 1
13/07/2009 | Registros faltantes: 1
14/07/2009 | Registros faltantes: 1
15/07/2009 | Registros faltantes: 1
16/07/2009 | Registros faltantes: 1
17/07/2009 | Registros faltantes: 1
18/07/2009 | Registros faltantes: 1
19/07/2009 | Registros faltantes: 1
20/07/2009 | Registros faltantes: 1
21/07/2009 | Registros faltantes: 1
22/07/2009 | Registros faltantes: 1
23/07/2009 | Registros faltantes: 1
24/07/2009 | Registros faltantes: 1
25/07/2009 | Registros faltantes: 1
26/07/2009 | Registros faltantes: 1
27/07/2009 | Registros faltantes: 1
28/07/2009 | Registros faltantes: 1
29/07/2009 | Registros faltantes: 1
30/07/2009 | Registros faltantes: 1
31/07/2009 | Registros faltantes: 1
01/08/2009 | Registros faltantes: 1
02/08/2009 | Registros faltantes: 1
03/08/2009 | Registros faltantes: 1
04/08/2009 | Registros faltantes: 1
05/08/2009 | Registros faltantes: 1
06/08/2009 | Registros faltantes: 1
07/08/2009 | Registros faltantes: 1
08/08/2009 | Registros faltantes: 1
09/08/2009 | Registros faltantes: 1
10/08/2009 | Registros faltantes: 1
11/08/2009 | Registros faltantes: 1
12/08/2009 | Registros faltantes: 1
13/08/2009 | Registros faltantes: 1
14/08/2009 | Registros faltantes: 1
15/08/2009 | Registros faltantes: 1
16/08/2009 | Registros faltantes: 1
17/08/2009 | Registros faltantes: 1
18/08/2009 | Registros faltantes: 1
19/08/2009 | Registros faltantes: 1
20/08/2009 | Registros faltantes: 1
21/08/2009 | Registros faltantes: 1
22/08/2009 | Registros faltantes: 1
23/08/2009 | Registros faltantes: 1
24/08/2009 | Registros faltantes: 1
25/08/2009 | Registros faltantes: 1
26/08/2009 | Registros faltantes: 1
27/08/2009 | Registros faltantes: 1
28/08/2009 | Registros faltantes: 1
29/08/2009 | Registros faltantes: 1
30/08/2009 | Registros faltantes: 1
31/08/2009 | Registros faltantes: 1
01/09/2009 | Registros faltantes: 1
02/09/2009 | Registros faltantes: 1
03/09/2009 | Registros faltantes: 1
04/09/2009 | Registros faltantes: 1
05/09/2009 | Registros faltantes: 1
06/09/2009 | Registros faltantes: 1
07/09/2009 | Registros faltantes: 1
08/09/2009 | Registros faltantes: 1
09/09/2009 | Registros faltantes: 1
10/09/2009 | Registros faltantes: 1
11/09/2009 | Registros faltantes: 1
12/09/2009 | Registros faltantes: 1
13/09/2009 | Registros faltantes: 1
14/09/2009 | Registros faltantes: 1
15/09/2009 | Registros faltantes: 1
16/09/2009 | Registros faltantes: 1
17/09/2009 | Registros faltantes: 1
18/09/2009 | Registros faltantes: 1
19/09/2009 | Registros faltantes: 1
20/09/2009 | Registros faltantes: 1
21/09/2009 | Registros faltantes: 1
22/09/2009 | Registros faltantes: 1
23/09/2009 | Registros faltantes: 1
24/09/2009 | Registros faltantes: 1
25/09/2009 | Registros faltantes: 1
26/09/2009 | Registros faltantes: 1
27/09/2009 | Registros faltantes: 1
28/09/2009 | Registros faltantes: 1
29/09/2009 | Registros faltantes: 1
30/09/2009 | Registros faltantes: 1
01/10/2009 | Registros faltantes: 1
02/10/2009 | Registros faltantes: 1
03/10/2009 | Registros faltantes: 1
04/10/2009 | Registros faltantes: 1
05/10/2009 | Registros faltantes: 1
06/10/2009 | Registros faltantes: 1
07/10/2009 | Registros faltantes: 1
08/10/2009 | Registros faltantes: 1
09/10/2009 | Registros faltantes: 1
10/10/2009 | Registros faltantes: 1
11/10/2009 | Registros faltantes: 1
12/10/2009 | Registros faltantes: 1
13/10/2009 | Registros faltantes: 1
14/10/2009 | Registros faltantes: 1
15/10/2009 | Registros faltantes: 1
16/10/2009 | Registros faltantes: 1
17/10/2009 | Registros faltantes: 1
18/10/2009 | Registros faltantes: 1
19/10/2009 | Registros faltantes: 1
20/10/2009 | Registros faltantes: 1
21/10/2009 | Registros faltantes: 1
22/10/2009 | Registros faltantes: 1
23/10/2009 | Registros faltantes: 1
24/10/2009 | Registros faltantes: 1
25/10/2009 | Registros faltantes: 1
26/10/2009 | Registros faltantes: 1
27/10/2009 | Registros faltantes: 1
28/10/2009 | Registros faltantes: 1
29/10/2009 | Registros faltantes: 1
30/10/2009 | Registros faltantes: 1
31/10/2009 | Registros faltantes: 1
12/04/2010 | Registros faltantes: 1
31/01/2011 | Registros faltantes: 1
09/05/2012 | Registros faltantes: 3
10/05/2012 | Registros faltantes: 1
11/05/2012 | Registros faltantes: 1
12/05/2012 | Registros faltantes: 1
13/05/2012 | Registros faltantes: 1
14/05/2012 | Registros faltantes: 1
11/03/2013 | Registros faltantes: 1
01/06/2013 | Registros faltantes: 1
31/05/2014 | Registros faltantes: 1
01/09/2014 | Registros faltantes: 1
12/09/2015 | Registros faltantes: 1
14/09/2015 | Registros faltantes: 1
01/06/2016 | Registros faltantes: 1
23/07/2016 | Registros faltantes: 1
25/07/2016 | Registros faltantes: 1
01/06/2017 | Registros faltantes: 1
26/09/2017 | Registros faltantes: 1
01/06/2018 | Registros faltantes: 1

In [131]:
# "1.- Eliminar rellenar nulos con la media de la columna"

# Imputamos los valores faltantes con la media de cada columna como se solicita en la asigancion
df["PRECIP"] = df['PRECIP'].fillna(df['PRECIP'].mean())
df["EVAP"] = df['EVAP'].fillna(df['EVAP'].mean())
df["TMAX"] = df['TMAX'].fillna(df['TMAX'].mean())
df["TMIN"] = df['TMIN'].fillna(df['TMIN'].mean())

In [132]:
# Mostramos un resumen estadistico una vez imputados los valores faltantes
# Notamos pequeñas variaciones respecto al anterior
df.describe()

             PRECIP          EVAP          TMAX          TMIN
count  19574.000000  19574.000000  19574.000000  19574.000000
mean       2.217452      4.882157     34.468808     16.657420
std        9.006565      2.263447      3.429615      6.247648
min        0.000000      0.000000     18.000000     -2.500000
25%        0.000000      3.200000     32.500000     11.000000
50%        0.000000      4.600000     35.000000     16.500000
75%        0.000000      6.400000     37.000000     23.000000
max      217.400000     15.600000     45.500000     29.000000

In [133]:
# Mostramos el numero de nulos una vez imputados los valores faltantes
df.isnull().sum()

PRECIP    0
EVAP      0
TMAX      0
TMIN      0
dtype: int64